### ISSUE TITLE
Question about how to use Casbin for ABAC at high scale

### ISSUE THREAD

**Issue by Melozzola** [casbin/casbin#101]
Hi, a few questions:
- Is there any other example (a part from the abac_model_ptc.conf) on how to use Casbin to implement ABAC?
- Given that I would like to use the ABAC model and given that I potentially have to enforce access to many different resources, what is the correct way to model it in Casbin?
In particular:
1. Is the policy definition not needed for ABAC? If it is needed how does it scales given that all the policies are loaded in memory? Is it possible to lazy load the policies in case?
2. Should I have a Model configuration per resource?
3. Should I create an Enforcer per resource? Isn't it too expensive?

**Comment by hsluoyz** [comment]
> Is there any other example (a part from the abac_model_ptc.conf) on how to use Casbin to implement ABAC?

There are no other examples for now. But you can try the examples in our policy editor: http://casbin.org/editor/.

> Given that I would like to use the ABAC model and given that I potentially have to enforce access to many different resources, what is the correct way to model it in Casbin?
In particular:

In Casbin's terminology, ABAC just means the feature that you can compare the properties of an object instead of an ID or a name. So ABAC is not a standalone and complete model but a feature that can be mixed with any other Casbin supported model.

And there is no such a "correct" way for a model. What model should be used is determined by your scenario. You can talk more about your scenario, so we can discuss how to model it in Casbin.

> 1. Is the policy definition not needed for ABAC? If it is needed how does it scales given that all the policies are loaded in memory? Is it possible to lazy load the policies in case?

In our particular ABAC example, no, the policy is not needed. Because it is the simplest example and just used to demonstrate the attribute usage of ABAC. However, if you mix ABAC with other models like RBAC, then the policy is probably required.

For policy enforcement at scale, we have a solution here: https://github.com/casbin/casbin#policy-enforcement-at-scale

> 2. Should I have a Model configuration per resource?

Probably not. The model represents the authorization logic. The only scenario I saw that needs multiple models, is a multi-tenant cloud environment, in which multiple tenant administrators need to specify Casbin model and policy for their own tenants. You should see if your scenario is similar to this case.

> 3. Should I create an Enforcer per resource? Isn't it too expensive?

You *can* have only one enforcer to perform all authorization checking. You can see our adopters: https://github.com/casbin/casbin#others, they mostly use one enforcer.

However, to improve the performance, we support multiple enforcers to provide load-balancing. See: https://github.com/casbin/casbin#policy-consistence-between-multiple-nodes

**Comment by Melozzola** [comment]
@hsluoyz thank you for the response. Some more details below:

> You can talk more about your scenario, so we can discuss how to model it in Casbin.
Suppose that I have millions of files and I want to implement permissions on those files. With "permission" I don't mean just r,w,e but a more complex scenario. Suppose that I have rules that could look like:

- File '/foo/bar/baz.txt' can be read only by users with role "REVIEWER" between 27/05/2018 and 31/05/2018 or can be read/written/deleted by System user only if the file is not locked
- File  '/README.txt' can be read by everyone but nobody can delete it. Only Admin can update it.
- File '/images/myImage.png' can be downloaded by any user belonging to the group "IMAGE_DOWNLOAD".

As you can understand each file might have very different permissions and it is somehow difficult (at least for me) to think about one single Model. The "matcher" expression would just explode.
On the other hand, ABAC would fit the requirements of such a generic permission use case. My 'object' could have numerous properties and I can write complex matchers (possibly adding more functions) to enforce the permissions.

> Policy enforcement at scale
I did read [this](https://github.com/casbin/casbin#policy-enforcement-at-scale) section but I still have my concerns. As far as I can understand you give the possibility to shard having different Nodes loading a subset of Policies. My understanding is that there can be a number of Nodes that will instantiate a single Enforcer with a particular Model which will load a shard of Policies. Those policies are loaded and kept in memory.
The first issue I see is memory consumption for big shards. Policies might be hundred of thousands in big systems. Anyway, this might be solved adding more nodes and splitting the shards or throwing in more memory in a single node. In the first case, where the scaling is horizontal, the load balancing algorithm needs to be smart and redirect the request to the node that has the policy loaded...feasible but not straight forward.
The second issue is that the enforcement is looping through all the policies every time, so loading a lot of policies would impact the 'enforce' performance.
Does the analysis above make sense? Am I missing something? Do you have some more insights?

Thank you very much.

**Comment by hsluoyz** [comment]
> As you can understand each file might have very different permissions and it is somehow difficult (at least for me) to think about one single Model. The "matcher" expression would just explode.

All the needs like time range can be realized by matcher, but the size of matcher will be large. Is the above three statements represent all the need? If not, maybe you need to have multiple enforcers (aka multiple matchers).

> In the first case, where the scaling is horizontal, the load balancing algorithm needs to be smart and redirect the request to the node that has the policy loaded...feasible but not straight forward.

If you use Casbin as a library, which is embedded in your business logic, then there is no need to load-balance, as you probably already get load balanced when the request enters your logic. Casbin library only contributes to minimal latency.

If you use Casbin as a service, then you should consider how to load the balance of Casbin authorization. I think it can still follow your load balancing strategy for your business logic. For example, if your backend file servers are sharded into five regions, then you can probably do the same sharing for Casbin.  Casbin is at least more light-weighted than your file server's processing, so sharding Casbin at the granularity of the business logic is viable.

> The second issue is that the enforcement is looping through all the policies every time, so loading a lot of policies would impact the 'enforce' performance.

Flexibility and efficiency are always a trade-off. Casbin chooses to have more flexibility by losing some performance. But there is still something can do to improve the performance:

1. Cache the decisions.
2. Use a first-apply effector. So once a rule is matched, its following rules will not be evaluated.
3. Have a better sharding, make the size of policy rules for an enforcer smaller.
4. Start multiple enforcers in a multi-threading manner in one node (a node usually has multiple cores). The synced enforcer is thread-safe.

**Comment by hsluoyz** [comment]
Closed as stale.

**Comment by harsimranb** [comment]
@hsluoyz I am looking to support ABAC for a CMS system, where there could be thousands to potentially even more ABAC checks.  Writing one long matcher isn't feasible in this case, nor is having multiple enforcers.  Is there any other workaround this?  An ABAC rule for us is something like `If user age is between 24 and 64, then they can "view" some "resource"`.  Any thoughts?

**Comment by hsluoyz** [comment]
@harsimranb , can you send a new issue?
