### ISSUE TITLE
[Question] RBAC w/ Resource Roles: Can I use domains in the policy model without using them in the request model?

### ISSUE THREAD

**Issue by cschappert** [casbin/casbin#1060]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

I want RBAC with resource roles and domains. For example:
p, admin, domain_1, widget, use
g, user_1, admin, domain_1
g2, object_1, widget, domain_1

user1 should be able to use object1

**However**, as the incoming request only lists the subject, object and action I would like my request model to look like:
r = sub, obj, act

The below seems to work, but as it's a bit different from anything in the docs, I wanted to check that I'm on the right track and won't been having problems.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, p.dom) && g2(r.obj, p.obj, p.dom) && r.act == p.act
```

**Your policy:**

```
p, admin, domain_1, widget, use
g, user_1, admin, domain_1
g2, object_1, widget, domain_1
```

**Your request(s):**

```
user_1, object_1, use ---> (expected: true)
```

**Comment by cschappert** [comment]
Just to be extra clear, I am using p.dom in the matcher where r.dom would normally be used. This seems to work, but is this a correct use of the g function?

`m = g(r.sub, p.sub, p.dom) && g2(r.obj, p.obj, p.dom) && r.act == p.act`

Thanks in advance for any help!

**Comment by hsluoyz** [comment]
@tangyang9464 @JalinWang

**Comment by JalinWang** [comment]
@cschappert Sorry for the late response.
It's okay to combine `RBAC w/ Resource Roles` with `RBAC w/ Domains`. 

I don't know your exact scenario, so I guess your model should be:
```
[request_definition]
r = sub, dom, obj, act
……
[role_definition]
g = _, _, _
g2 = _, _

[matchers]
m = g(r.sub, p.sub, r.dom) && g2(r.obj, p.obj) && r.dom == p.dom && r.act == p.act
```
Explanation:
1. You need to include `dom` in the `request_definition` for domain checking. Otherwise, for `user_1, object_1, use ---> (expected: true)`, `user_1` may not have `admin` role in other domains and  you need to specify in which domain you want to check, e.g., `user_1, domain_1, object_1, use`. 
2. `p.dom` represents the domain in the policy while `r.dom` refers to the domain in the request. They should correspond which is ensured by `r.dom == p.dom`. Hence, `g(r.sub, p.sub, p.dom)` and `g(r.sub, p.sub, r.dom)` are both okay.
3. There is no need to incorporate a domain into resources. Checking the subject's domain is enough. Reference: https://casbin.io/docs/rbac-with-domains

Test code:
```go
func TestCust(t *testing.T) {
	text :=
		`
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && g2(r.obj, p.obj) && r.dom == p.dom && r.act == p.act
`
	m, _ := model.NewModelFromString(text)
	// The above is the same as:
	// m := NewModel()
	// m.LoadModelFromText(text)

	e, _ := NewEnforcer(m)

	_, _ = e.AddNamedGroupingPolicy("g", "user_1", "admin", "domain_1")
	_, _ = e.AddNamedGroupingPolicy("g2", "object_1", "widget")
	_, _ = e.AddPolicy("admin", "domain_1", "widget", "use")

	testDomainEnforce(t, e, "user_1", "domain_1", "object_1", "use", true)
}
```
Hoping this will help you.

**Comment by cschappert** [comment]
@JalinWang Thank you for your reply! Yes, my main question was whether it was possible to have something like
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
```
and use groupings to determine the dom of the sub from the request.

From your answer it seems that this is not possible, so you have answered my question. Thank you for the help!
