### ISSUE TITLE
[Question] Is there any better design?

### ISSUE THREAD

**Issue by Rainshaw** [casbin/casbin#1094]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
hello, first of all, thanks for your excellent work on this project. I am nearly a beginner and have search and read issues about my qustion, but I still have some questions.

Let me describe my scenery:
1. I need a global admin role, and any one belongs to it have almost all actions on all resources.
2. each resource have its owners and operators.

I searched the issue and docs, but do not find a good way to achieve this, so I start to design it. Thanks for the ability of casbin which can combine RBAC with ABAC, I design the model and policy below.

**Your model:**

```ini
[request_definition]
r = sub, act
r2 = sub, obj, act

[policy_definition]
p = sub, act, eft
p2 = sub, sub_rule, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))
e2 = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub) && regexMatch(r.act, p.act)
m2 = (p2.obj == "*" || r2.obj.ID == p2.obj) && (p2.sub == "*" || r2.sub == p2.sub) && regexMatch(r2.act, p2.act) && (p2.sub_rule == "" || eval(p2.sub_rule))
```

**Your policy:**

```
p, admin, .*, allow
g, Rainshaw, admin

p2, *, r2.sub in r2.obj.Owners, *, .*, allow
p2, *, (r2.sub in r2.obj.Operators) && r2.act != "delete", *, .*, allow
```

**Your request(s):**

```
# EnforceContext("1")
Rainshaw, create ---> true (expected: true)
Rainshaw, delete ---> true (expected: true)
```
```
# EnforceContext("2")
alice, {Owners: ["alice"], Operators: ["bob"]}, create ---> true (expected: true)
bob, {Owners: ["alice"], Operators: ["bob"]}, create ---> true (expected: true)
alice, {Owners: ["alice"], Operators: ["bob"]}, delete ---> true (expected: true)
bob, {Owners: ["alice"], Operators: ["bob"]}, delete ---> false (expected: false)
```
And, I store the Owners and Operators in database, and read it when build EnforceRequest.
so, my question is whether there is better way to achieve it. And if there is not any better way, should we put this solution in docs or somewhere else, as for this scenery is really common.

**Comment by hsluoyz** [comment]
@JalinWang 

/cc @tangyang9464

**Comment by tangyang9464** [comment]
@RainshawGao  some advices：
1. use ``some(where (p.eft == allow))`` instead of ``some(where (p.eft == allow)) && !some(where (p.eft == deny))``
unless you have unmet needs
2. Create roles ``Owner`` and ``Operator``, then assign roles to ``alice`` and ``bob`` instead of using ``in`` and ``eval``
```
g, alice, Owner
g, bob, Operator
```
4. ``(r2.sub in r2.obj.Operators)`` should be placed directly in ``mather``, using ``eval`` is redundant. see [special-grammer](https://casbin.org/docs/en/syntax-for-models#special-grammer)

**Comment by RainshawGao** [comment]
@tangyang9464 thanks for your reply, as for the first advice, I have some other actions which will be denied when sub_rule returns true, so I have to use it.

And the second advice is really confused me since I know casbin. How can I achieve different owners  and operators for different objects? The users assign to Owner will match `g(r2.sub, p2.sub)` for different resource objects. If there is something wrong  with my opinion, hope you can point out for me. 

The forth(may be a typo, third) advice, if I placed it in mather, the mather will be really long, as below:
```
m2=m2 = (p2.obj == "*" || r2.obj.ID == p2.obj) && (p2.sub == "*" || r2.sub == p2.sub) && regexMatch(r2.act, p2.act) && ((r2.sub in r2.obj.Operators)&&r2.act != "delete" || (r2.sub in r2.obj.Owners)) && (p2.sub_rule == "" || eval(p2.sub_rule))
```
I need to write the sub_rule into matcher, will this be precompiled for performance? If no, I prefer to store it in sub_rule for convenience.

**Comment by tangyang9464** [comment]
@RainshawGao 
1. Assign a role ``Owner`` to each ``object``, such as ``object1::Owner``. I think the performance is better than storing ``Owner``  in the database, and then read it every request and use ``in`` and ``eval`` to calculate. You can try to compare the performance of the two to decide.
2. matcher compilation will be cached. And ``eval`` instead adds extra compilation overhead, it seems that you use ``eval`` just to use ``in``, I think it's superfluous since you can use the ``in`` syntax directly in the matcher. My idea is just to replace ``(p2.sub_rule == "" || eval(p2.sub_rule))`` with ``(r2.sub in r2.obj.Operators)``

**Comment by RainshawGao** [comment]
@tangyang9464  I did a benchmark and find that eval is much better than more roles, here is my code
```go
package benchmark

import (
	"fmt"
	"github.com/casbin/casbin/v2"
	"testing"
)

func BenchmarkManyRole(b *testing.B) {
	e, _ := casbin.NewEnforcer("example/many_role_model.conf")
	for i := 0; i < 10000; i++ {
		e.AddGroupingPolicy(fmt.Sprintf("alice%d", i), fmt.Sprintf("owner:%d", i))
		e.AddGroupingPolicy(fmt.Sprintf("bob%d", i), fmt.Sprintf("owner:%d", i))
		e.AddGroupingPolicy(fmt.Sprintf("carol%d", i), fmt.Sprintf("operator:%d", i))
		e.AddGroupingPolicy(fmt.Sprintf("david%d", i), fmt.Sprintf("operator:%d", i))
		e.AddPolicy(fmt.Sprintf("owner:%d", i), fmt.Sprintf("data%d", i), ".*", "allow")
		e.AddPolicy(fmt.Sprintf("operator:%d", i), fmt.Sprintf("data%d", i), ".*", "allow")
		e.AddPolicy(fmt.Sprintf("operator:%d", i), fmt.Sprintf("data%d", i), "delete", "deny")
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		obj := fmt.Sprintf("data%d", i)
		e.Enforce(fmt.Sprintf("alice%d", i), obj, "create")
		e.Enforce(fmt.Sprintf("alice%d", i), obj, "delete")
		e.Enforce(fmt.Sprintf("bob%d", i), obj, "create")
		e.Enforce(fmt.Sprintf("bob%d", i), obj, "delete")
		e.Enforce(fmt.Sprintf("carol%d", i), obj, "create")
		e.Enforce(fmt.Sprintf("carol%d", i), obj, "delete")
		e.Enforce(fmt.Sprintf("david%d", i), obj, "create")
		e.Enforce(fmt.Sprintf("david%d", i), obj, "delete")
	}
}

func BenchmarkEval(b *testing.B) {
	e, _ := casbin.NewEnforcer("example/eval_model.conf", "example/eval_policy.csv")

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		obj := struct {
			Owners    []interface{}
			Operators []interface{}
		}{
			Owners:    []interface{}{fmt.Sprintf("alice%d", i), fmt.Sprintf("bob%d", i)},
			Operators: []interface{}{fmt.Sprintf("carol%d", i), fmt.Sprintf("david%d", i)},
		}
		e.Enforce(fmt.Sprintf("alice%d", i), obj, "create")
		e.Enforce(fmt.Sprintf("alice%d", i), obj, "delete")
		e.Enforce(fmt.Sprintf("bob%d", i), obj, "create")
		e.Enforce(fmt.Sprintf("bob%d", i), obj, "delete")
		e.Enforce(fmt.Sprintf("carol%d", i), obj, "create")
		e.Enforce(fmt.Sprintf("carol%d", i), obj, "delete")
		e.Enforce(fmt.Sprintf("david%d", i), obj, "create")
		e.Enforce(fmt.Sprintf("david%d", i), obj, "delete")
	}
}
```
```
# many_role_model.conf
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = r.obj == p.obj && g(r.sub, p.sub) && regexMatch(r.act, p.act)
```
```
#eval_model.conf
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, sub_rule, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = p.obj == "*" && p.sub == "*" && regexMatch(r.act, p.act) && (p.sub_rule == "" || eval(p.sub_rule))
```
```
#eval_policy.conf
p, *, r.sub in r.obj.Owners, *, .*, allow
p, *, (r.sub in r.obj.Operators) && r.act != "delete", *, .*, allow
```

**Comment by RainshawGao** [comment]
and for the second point, I think replace `(p2.sub_rule == "" || eval(p2.sub_rule))` with `(r2.sub in r2.obj.Operators)` did work for me. if use this, how can a request.user in owners matche a policy? so it is not a good idea.
Thanks for your time and reply.
