### ISSUE TITLE
[Question] How to get the list of subjects

### ISSUE THREAD

**Issue by damienmiheev** [casbin/casbin#1095]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
What API should i use (and which one is most performance) to get the list of users by resource.
I need something like this:
```
val subjects = enforcer.getSubjectsByObject("data1")

subjects == ["alice", "bob"]
```

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && r.act == p.act
```

**Your policy:**

```
p, org1_admins, project-data, read
p, org2_admins, project-data, read

g, alice, org1-admins
g, bob, org2-admins
g2, data1, project-data
g2, data2, project-data
```

**Comment by JalinWang** [comment]
@damienmiheev You can use`GetFilteredPolicy()` to filter policies by the object field and then extract subjects.

There seem to be many scenes and we can't cover them all. Similar to https://github.com/casbin/casbin/issues/1030#issuecomment-1166202754 https://github.com/casbin/casbin/issues/1036

**Comment by damienmiheev** [comment]
@JalinWang thats how i did it previously, when using ACL model.

But for now there is no `data` object in policy list, thee is `project-data` group.
So theoretically i can get userGroup by userId, dataGroup by dataId, and then manually combine them.

But this is at least 3 request to enforcer.
So if i understand correctly there is no build in api for such cases.

Right now i'm doing something like this:
1. fetching all potential userIds from project db
2. do `batchEnforce` operation on set of (userId, resourceId, 'read')
3. filter list of users based on result of batchEnforce

But it is not very efficient. So i was interesting maybe i missed something...

**Comment by tangyang9464** [comment]
@damienmiheev 
1. use ``GetImplicitRolesForUser("data1")`` get ``["project-data"]``
2. use ``GetFilteredPolicy`` get ["org1_admins", "org2_admins"]
If you use a database such as MySQL, you can also choose to filter by writing sql statements
3. use ``GetImplicitUsersForRole("org1_admins")`` and ``GetImplicitUsersForRole("org2_admins")`` get ``["alice", "bob"]`` 

All in all, you can filter by combining (rbac_api)[https://casbin.org/docs/en/rbac-api] and ``GetFilteredPolicy`` (or SQL) without having to use ``enforce`` because it has nothing to do with authentication

**Comment by hsluoyz** [comment]
Closed as resolved
