### ISSUE TITLE
Casbin only takes string parameters(Note for others).

### ISSUE THREAD

**Issue by IvRRimum** [casbin/casbin#113]
Just wanted to make a note for everybody else(Most likely it can be resolved from model)

Example:

```
p, 0, /v1/login, read
p, 0, /v1/register, read
p, 2, /v1/home, read
```

Doesn't work:
```
var currentUserType int
if auth_rules.AuthEnforcer.Enforce(currentUserType, r.URL.Path, "read") == true {
```

Works(Convert int into string and then pass it to the Enforcer):
```
var currentUserType int
if auth_rules.AuthEnforcer.Enforce(strconv.Itoa(currentUserType), r.URL.Path, "read") == true {
```

**Comment by hsluoyz** [comment]
Thanks for pointing it out.

Casbin treats the ``pvals`` elements in a policy rule (like ``p, 0, /v1/login, read``) as strings, because there's no way to tell Casbin what the type is. And when you provide integer arguments in ``Enforce()`` as ``rvals``, Casbin will compare ``pvals`` against ``rvals`` in the matcher. And the string ``"0"`` won't equal integer ``0``.

If there is anyone thinking this issue should be fixed in some way, we can discuss about it:)

**Comment by IvRRimum** [comment]
I think this is more of convenience thing, definitely not in the priority list IMO.

Few ideas:
1) We could check the type of the identifier and then compare them with the type that is passed in.
2) We could add ability for user to define type in policies file ex `p, 011:int, /v1/login, read`. 
3) Add note in README(haven't checked, might already be there tho).


Amazing package,
Thanks!

**Comment by ColmBhandal** [comment]
> It complicates things and also needs to escape.

Just a thought. It would probably be less complicated to escape if we typed the argument at the policy definition level rather than the policy rule level. Since policy rules are storing the actual values of items, then yeah, I'd imagine escaping would be a bit complicated. But for policy definitions, we're just defining variable names, and in that case surely it would be OK for Casbin to reserve some special characters such as ":" for type? Of course, there would still be some work to parse such expressions for their types, and I agree with (https://github.com/IvRRimum) that this isn't a top priority.
