### ISSUE TITLE
[Question] Is SyncedCachedEnforcer production Ready or safe for production usage consumption a.k.a GA released?

### ISSUE THREAD

**Issue by atreyamj** [casbin/casbin#1250]
**What's your scenario? What do you want to achieve?**
Hi team, 
Thank you so much for all the great contribution to opensource and an awesome family of libraries. Casbin is light years ahead of most RBAC open source libraries I have researched. 

I work at a small startup and Given how well built casbin is, we are planning it us it for our production use-case. As I was exploring the [casbin docs docs](https://casbin.org/docs/enforcers), I wanted to use Cached Enforcer and implement my own go-routine to async refresh the cache. However, I realized by looking the repo and code that there's a `SyncedCachedEnforcer` which combines both the Cached Enforcer and Synced Enforcer. However, I did NOT see a mention of `SyncedCachedEnforcer` on the official doc. 

Hence, I wanted to check with you folks if it is safe use `SyncedCachedEnforcer` for production use-case just like Cached Enforcer? Is `SyncedCachedEnforcer` stable / GA released ? Curious to see why this was not added in the doc ?

Thank You!
Atreya Joshi

**Comment by PokIsemaine** [comment]
Thanks to your feedback, `SyncedCachedEnforcer` is a relatively new feature and basically usable. However, due to the lack of long-term practice, it may also have some hidden problems, if you encounter problems, you can report to us through issues. 
In addition, we will be adding documentation for `SyncedCachedEnforcer` recently, so sorry for the bother

**Comment by atreyamj** [comment]
Perfect, this is super helpful! Thank you so much ! I really appreciate it !
