### ISSUE TITLE
db adapter for many resources with ABAC

### ISSUE THREAD

**Issue by vtolstov** [casbin/casbin#128]
If i have is about 3000-10000 users with each have 5-10 resources, so i need in peak 10*10000=100000 lines. If i use db, i can fetch only partial lines - for example only for affected user. Does it right solution?
(I fetch lines based on uuid of user that i have from oauth2 token)

**Comment by hsluoyz** [comment]
You can use an adapter that supports ``filtered policies``. With it you can only load a subset of the policy rules into the local enforcer's memory. See: https://github.com/casbin/casbin#policy-enforcement-at-scale

**Comment by vtolstov** [comment]
Thanks! But if i have for example central point, that manages 4-5 datacenters and some users have access to only one location, but other have access to all. As i understand i can't use filter?

**Comment by hsluoyz** [comment]
You can shard the policy rules based on any elements including ``subject``, ``object``, etc. You should choose the element based on your requirement.

**Comment by vtolstov** [comment]
I have grpc server that for example accepts request KeyAdd, KetLst, KeyDel, KeyGet, KeySet.

Each user belongs to zones - public, or zone1, zone2, zone3

I have users and for some of them i have KeyLst and KeyGet allow for public, zone1 and zone2, but not zone3
For some users i have all Key* acts for zone1, but not public and other zones.

How can i shard policy in this case?

**Comment by hsluoyz** [comment]
So the scenario has four elements:

- ``sub``: the user name or ID
- ``sub_zone``: the zone user belongs to like ``public, or zone1, zone2, zone3``
- ``obj``: the operation user can do like ``KeyAdd, KetLst, KeyDel, KeyGet, KeySet``
- ``obj_zone``: the zone operation belongs to like ``public, or zone1, zone2, zone3``

The sharding can be based on any one field in the above. So you have four choices.

1. How many partitions do you want to shard into? If you shard against ``sub_zone`` or ``obj_zone``, you probably end into 4 partitions, because you only have 4 zones.

2. If you want to have more partitions, you can shard on ``sub``, for example, you have 10000 users with ID from 0 to 9999, you want to have 10 partitions. Then you can shard 0-999 into partition 1, 1000-1999 into partition 2, and so on..

3. Do not shard on an element that has regex, e.g., ``KeyAdd | KetLst`` or ``.*``. Because the filtered adapter does not know how to shard the regex, it only shards the elements literally.

**Comment by vtolstov** [comment]
Thanks! great help! And how code looks like? (i'm need simple example only)

**Comment by hsluoyz** [comment]
How to retrieve the policy rules only for ``domain1``: https://github.com/casbin/casbin#policy-enforcement-at-scale

The source code of filtered adapter is: https://github.com/casbin/casbin/blob/master/persist/file-adapter/adapter_filtered.go. You can refer to it if you want to implement your own filtered adapter.

**Comment by vtolstov** [comment]
For example i want to shard by sub_zone, in this case instead of domain1 i need to specify sub_zone - public, zone1, zone2 or no?
```
   P: []string{"", "domain1"},
   G: []string{"", "", "domain1"},
```

**Comment by hsluoyz** [comment]
Yes

**Comment by vtolstov** [comment]
if this is not very hard to you, can you provide me 3-4 lines contents of file for file-adapter?

**Comment by hsluoyz** [comment]
First, please provide your final model and policy example. Then we can know how to customize the filtered file adapter.

**Comment by vtolstov** [comment]
thanks for help, i have another question about filtered adapter.
As i understand in case of big policy (as you benchmark 1000000 records) and filtered adapter i need to provide single threaded service (FIFO) or use multi-threaded with mutex?
So for each request i need to load filtered policy, enforce and return result.
May be provide some caching results...
Does this looks right?

**Comment by vtolstov** [comment]
So i need to have pool of *casbin.Enforcer?

**Comment by hsluoyz** [comment]
You can refer to our Casbin Server project: https://github.com/casbin/casbin-server
