### ISSUE TITLE
[Feature] Support map as well as structs in ABAC

### ISSUE THREAD

**Issue by mih-kopylov** [casbin/casbin#1328]
**Is your feature request related to a problem? Please describe.**
Currently, I have to pass a struct in order to verify a request with ABAC policy https://casbin.org/docs/abac .
In certain cases, model can have dynamic structure, like customer-defined, and therefore, there might be no struct in code that can be filled and passed to `Enforce` method.

**Describe the solution you'd like**
In such cases it'd be nice to be able to pass a `map` as a request parameter.
Like this:
```
subject - userId:15
object - { Url: '/book/111', Owner: 'userId:15' }
method - PUT
```
`object` is a map here.
And the model might have something like

```
[matchers]
m = (r.sub == r.obj.Owner || (g(r.sub, p.sub) && keyMatch(r.obj.Url, p.obj))) && (r.method == p.method)
```

**Describe alternatives you've considered**
Can't find any alternatives at the moment

**Additional context**
-

**Comment by abichinger** [comment]
I faced the same issue. The problem is that [govaluate](https://github.com/Knetic/govaluate) (library used by casbin to evaluate expressions) does not support maps.

I have created a [fork](https://github.com/abichinger/govaluate) with map support. [This](https://github.com/abichinger/govaluate/commit/74b96f998566865a6e53d5ebf898127346f72810) is the relevant commit.

**Comment by hsluoyz** [comment]
@abichinger hi, can you make a PR to our own fork: https://github.com/casbin/govaluate ?

**Comment by abichinger** [comment]
@hsluoyz hi, Yes I can make a PR but,

https://github.com/casbin/govaluate is not a real fork of https://github.com/Knetic/govaluate. What I mean is that `casbin/govaluate` does not link to `Knetic/govaluate`

Therefore GitHub won't let me make a PR from https://github.com/abichinger/govaluate
`casbin/govaluate` should be recreated with the fork button on GitHub

**Comment by hsluoyz** [comment]
@abichinger we don't keep the "fork" label in GitHub because it assumes that https://github.com/casbin/govaluate will probably not go back to https://github.com/Knetic/govaluate any more, given that it seems to have been deprecated (last commit is in 2017)

I don't have strong opinion to maintain a hard-fork from: https://github.com/abichinger/govaluate . The starting point is just that https://github.com/abichinger/govaluate is not a good choice, given it's personal repo (if username is renamed, then we crash). So I trust org repos more. And it seems that https://github.com/Knetic/govaluate won't accept your PR in short time (given last commit is in 2017), a good option for now is hosting the repo in our own org.

You should fork directly from: https://github.com/casbin/govaluate , then you can create PR

**Comment by abichinger** [comment]
Looks like casbin already supports json (#1277)
```go
e.EnableAcceptJsonRequest(true)
// ...
bytes, err := json.Marshal(obj)
e.Enforce(sub, string(bytes), act)
```
Although, I glanced over the implementation and saw that regular expressions are used, which in my opinion could cause problems
