### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by sagarve** [casbin/casbin#1362]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Hi, I'm new to casbin and wanted to understand if below usecases can be implemented using casbin. First, I'd like to explain in brief about my application, it's a multi-tenant app for which we've created separate schemas in our postgres db to store information related to each client separately.

Usecases:
- Roles and permissions shared by all clients.
- Custom roles, which clients can create for themselves and they'll be specific to the client that created them.
- User groups. I want to assign permissions based on individual users and user groups inside an organisation.
- I want to create/modify/revoke user access, manage roles and user groups from my application's UI.
- I want to maintain all my data in postgres db.

I'm using `casbin-django-orm-adapter` in my django app to integrate with casbin. I'm facing below issues:
1. Is it possible to keep policies related to user groups, roles-permissions and user access policies in separate DB tables and enforce using data from multiple tables? Because if I keep everything in the same table, it becomes slightly unmanageable.
2. I want to enforce access control on APIs (ACL) and access control based on users and resources (RBAC). Do I need two models and enforcers to implement this? If yes, can you plz share any documentation regarding that?

**Your model:**

```ini
[request_definition]
r = sub, act, obj

[policy_definition]
p = sub, act, obj

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && g(p.act, r.act) && p.obj == r.obj
```

**Your policy:**

```
p, user1, w-admin, w1
p, user1, w-editor, p1

g, w-admin, read
g, w-admin, write
g, w-admin, create
g, w-admin, delete
g, w-editor, read
g, w-editor, write
```

**Your request(s):**

```

```

**Comment by hsluoyz** [comment]
Hey @sagarve , I have to say, such kind of questions are not welcomed. This is a place more about Casbin instead of sharing your company's scenario. And the docs is just here: https://casbin.org/ . Don't ask "low-hanging-fruit" questions before checking the docs carefully. Most of your questions show that you know very little about Casbin.

The community's goal is to evolve the open source project based on its own roadmap and it's not a place to serve your company only (and the community people don't like helping doing the homework that your boss told you to do :(). I hope I have made it clear now.

I noticed that you have asked a lot of such questions across many of our repos. Stop doing that please and this is a kind of warning :)
