### ISSUE TITLE
How to define Admin role to access everything in every domain?

### ISSUE THREAD

**Issue by CHCP** [casbin/casbin#154]
Another question: There is a Admin role and a admin user, this role can read and write every thing in every domain. I defined matchers as follow, but it did not work. How do I use the r.sub? Thanks.

```ini
[matchers]
m = g(r.sub, p.sub, r.dom) && keyMatch2(r.obj, p.obj) && (r.act == p.act || p.act == "ANY")  || (r.sub == "Admin")
```

The policy:

```csv
g, admin, Admin, ALL
```

**Comment by CHCP** [comment]
In my project, ANY means all methods in RESTful api, and ALL means all domains. 
I don't understand what your mean, could you please explain this better? Thanks.

**Comment by hsluoyz** [comment]
OK. I misunderstood it. Your scenario is like a cloud computing platform, e.g., OpenStack. You want to have a global admin team that can manage every tenant.

You can use the RBAC without domain (the default RBAC) as the RBAC for all domains. You can use a matcher like:

```ini
[matchers]
m = (g(r.sub, p.sub, r.dom) || g2(r.sub, "Admin")) && keyMatch2(r.obj, p.obj) && (r.act == p.act || p.act == "ANY")  || (r.sub == "Admin")
```

Then use policy like:

```csv
g, alice, Admin, domain1
g2, admin, Admin
```

So ``alice`` is an administrator for ``domain1``, it can make ``g(r.sub, p.sub, r.dom)`` to be true. ``admin`` is a global administrator, it can make ``g2(r.sub, "Admin")`` to be true.

**Comment by CHCP** [comment]
Yes, I think it is works. Thanks a lot.

I delete the last code " || (r.sub == "Admin") ",  and it is works well. What is the code means?  Can I delete the code "|| (r.sub == "Admin")"?

**Comment by hsluoyz** [comment]
``|| (r.sub == "Admin")`` is something you provided, you didn't know what it means? In my view, it means when the subject in the request is ``Admin``, everything should be permitted. But in the information you provided, ``Admin`` is a RBAC role instead of a user name. You use the lower-cased ``admin`` as the user name instead. So ``r.sub`` will never be ``Admin`` as I see it. The assertion: ``r.sub == "Admin"`` will always be false. So it can be removed without any difference.
