### ISSUE TITLE
How to enforce a hierarchy of sub-tenants/domains?

### ISSUE THREAD

**Issue by jrmullins** [casbin/casbin#270]
I'm trying to use a hierarchy of tenants to enforce access control with Casbin.

Suppose we have company A which is a parent of company B. 
I want to enforce a relationship where company A can access company B's resources but company B can not access company A's.

How would this be done with a model and policy?

**Comment by hsluoyz** [comment]
Hi @jrmullins , I assume you are using the RBAC with Domains model:

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
```

and policy:

```
p, admin, domain1, data1, read
p, admin, domain1, data1, write
p, admin, domain2, data2, read
p, admin, domain2, data2, write
g, alice, admin, domain1
g, bob, admin, domain2
```

We can simply use another RBAC system: ``g2`` on the tenant/domain to add the inheritance:

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && g2(r.dom, p.dom) && r.obj == p.obj && r.act == p.act
```

Policy:

```
p, admin, domain1, data1, read
p, admin, domain1, data1, write
p, admin, domain2, data2, read
p, admin, domain2, data2, write
g, alice, admin, domain1
g, bob, admin, domain2
g2, domain2, domain1
```

**Comment by jrmullins** [comment]
Hmm I copied and pasted your model and policy into the casbin editor https://casbin.org/en/editor and tested the following requests:

```
1. alice, domain1, data1, read = true
2. alice, domain2, data1, read = false
3. alice, domain3, data1, read = false
4. bob, domain1, data1, read = false
```
I would have expected line 2 to be true.

Requests 1, 3, and 4 make sense to me. If I add `g2, domain3, domain2` to the policy I would expect line 3 to be true but it remains false.

**Comment by hsluoyz** [comment]
Can you try it in Go?

**Comment by jrmullins** [comment]
I got the same results in golang
```
func main() {
	e := casbin.NewEnforcer("model.conf", "policies.csv")
	var allowed bool

	allowed = e.Enforce("alice", "domain1", "data1", "read")
	fmt.Println(allowed)

	allowed = e.Enforce("alice", "domain2", "data1", "read")
	fmt.Println(allowed)

	allowed = e.Enforce("alice", "domain3", "data1", "read")
	fmt.Println(allowed)

	allowed = e.Enforce("bob", "domain1", "data1", "read")
	fmt.Println(allowed)
}
```

```
true
false
false
false
```

**Comment by jrmullins** [comment]
I get the same results if I remove the `r.obj == p.obj` from the matcher so it ignores `data1` vs `data2`

**Comment by hsluoyz** [comment]
``g2, domain2, domain1`` means domain2 inherits domain1.

**Comment by jrmullins** [comment]
Since domain1 is the parent company I want domain1 to inherit domain2. If I change the policies I still seem to get the incorrect results:

policies.csv
```
p, admin, domain1, data1, read
p, admin, domain1, data1, write
p, admin, domain2, data2, read
p, admin, domain2, data2, write
g, alice, admin, domain1
g, bob, admin, domain2
g2, domain1, domain2   <-- i want domain1 to inherit domain2
g2, domain2, domain3  <-- i want domain2 to inherit domain3
```

```
alice, domain1, data1, read => true
alice, domain2, data2, read => false
alice, domain3, data1, read => false
bob, domain1, data1, read => false
```

I still would expect lines 2 and 3 to be true but they are not. With the following matcher:
`m = g(r.sub, p.sub, r.dom) && g2(r.dom, p.dom) && r.act == p.act`

**Comment by hsluoyz** [comment]
Sorry for the late response. It seems that Casbin doesn't support such a feature now.

**Comment by jrmullins** [comment]
Thats too bad. In our company, we have many tenant/companies that administer sub tenants. I suppose these relationships could be hard coded in the model's matcher, but we are dealing with ~15k tenants. I am not sure how much that affects the performance of the model.

Any suggestions how to handle this?

**Comment by hsluoyz** [comment]
Hi @jrmullins ,

I re-thought this issue and found an important question: what does `r.dom` refer to? 

```
alice, domain1, data1, read => true
alice, domain2, data2, read => false <-- should be true
alice, domain3, data1, read => false <-- should be true
bob, domain1, data1, read => false
```

Why are you passing `domain2` and `domain3` for 2nd and 3rd statement? If you pass `domain1` to `r.dom`, it will work.

A deeper question is that does your user (like alice) have a belonging tenant?

- If yes, and the belonging tenant for `alice` is `domain1`. Then you should pass `domain1` to `r.dom`.
- If no, it should be * to traverse all domains that `alice` is possibly in.

**Comment by jrmullins** [comment]
@hsluoyz r.dom refers to the request domain/tenant/company. In our system, we have many dom(companies) and those companies have sub-companies. We want top level companies to be able to access their sub-company resources.

**Comment by jrmullins** [comment]
It would be both.

Example:
A company's resource would only be accessible to that company's users or users of its parent company.

**Comment by hsluoyz** [comment]
Let's say your example:

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && g2(r.dom, p.dom) && r.act == p.act
```

```csv
p, admin, domain2, data2, read
g, alice, admin, domain1
g2, domain1, domain2   <-- i want domain1 to inherit domain2
```

```
alice, domain2, data2, read => false <-- should be true
```

Given the request and the only `p` policy, we have:

`g(r.sub, p.sub, r.dom) && g2(r.dom, p.dom)` -> `g("alice", "admin", "domain2") && g2("domain2", "domain2")`. This part: `g("alice", "admin", "domain2")` is false because alice is not an admin in domain1. And the g2 is useless.

If you assign `domain1` to r.dom, it would be perfect: `g(r.sub, p.sub, r.dom) && g2(r.dom, p.dom)` -> `g("alice", "admin", "domain1") && g2("domain1", "domain2")`. Both g1 and g2 are true. The request will be allowed.

So the question is why r.dom cannot be `domain1`?

**Comment by jrmullins** [comment]
Ah! I understand now. I was writing my requests wrong. This works!

Documenting for anyone looking in the future.
Model 
```
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && g2(r.dom, p.dom) && r.obj == p.obj && r.act == p.act
```

Policy
```
p, admin, domain1, data1, read
p, admin, domain2, data2, read
p, admin, domain3, data3, read
g, alice, admin, domain1
g, bob, admin, domain2
g, carol, admin, domain3
g2, domain1, domain2
g2, domain2, domain3
```

Requests
```
alice, domain1, data1, read => true
alice, domain1, data2, read => true
alice, domain1, data3, read => true
bob, domain2, data1, read => false
bob, domain2, data2, read => true
bob, domain2, data3, read => true
carol, domain3, data1, read => false
carol, domain3, data2, read => false
carol, domain3, data3, read => true
```

Everything works as expected. Thanks again!

**Comment by WesleyBatista** [comment]
Based on the example above I wanted to extend the hierarchy idea also to roles, so in addition to the domains inheritance we would have for example:
```
# groups hierarchy
g3, admin, member
g3, member, anonymous
```

What I wanted was that _admin_ inherits all capabilities from _member_ role, and _member_ from _anonymous_, so the set of permissions for admin keeps short and easy to maintain.


I fell short on implementing the `rbac_model.conf` for this. Even worse, I found out that I have some misunderstanding on the solution presented above.

Because **alice** is **admin** on `domain1`, and `domain1` inherits from `domain2`, which in turn inherits from `domain3`, I was expecting **alice** to have access to **data2** and **data3** from the other domains as well, but this is not true :confused: 

![image](https://user-images.githubusercontent.com/755254/103183896-8c983d80-48b5-11eb-9ae9-8d0d82fcda4b.png)


Already spend the whole day on this. Could someone help me out? :persevere:  _(perhaps with a model config meeting the specification I shared here? :pray: )_

**Comment by hsluoyz** [comment]
@WesleyBatista in the RBAC with domains model, a role belongs to a domain instead of global. So alice is domain1's admin doesn't   mean that she has any permission for other domains. You need to set permissions for alice in other domains.

**Comment by WesleyBatista** [comment]
> **_1. Set permissions for alice in other domains._**

I know this ultimately would work, but I want to avoid replicating permissions based on users, to keep the config as small and maintainable as possible, as the application grows with the number of features/resources.


> **_2. Use global roles (two underscores) for g._**

Not sure if I got this right, but with this option it seems to have solve the "problem" partially:

![image](https://user-images.githubusercontent.com/755254/103220964-ce5ecd80-4921-11eb-9f2e-b1c1a62ea5f3.png)

But now I can not answer the question: **which domain this user belongs to?**
___
On the model that I would like to implement, users should just be assigned to a group in a domain in order to get permissions; `domain` can inherit from another `domain`;  `role` can inherit from another `role`;

I was playing with the [editor](https://casbin.org/en/editor) and I came up with these policies:
```ini
p, admin, *, *
p, admin, domain1, create_post
p, member, *, create_post
p, member, *, create_something_else
p, member, *, see_private_pages
p, anonymous, *, see_public_pages

# users assignments
g, alice, admin, domain1
g, bob, member, domain2
g, carol, member, domain3

# tenants hierarchy
g2, domain1, domain2
g2, domain2, domain3

# roles hierarchy
g3, admin, member
g3, member, anonymous
```

Then, based on the [example of how to implement the inheritance with domains](https://github.com/casbin/casbin/issues/270#issuecomment-538033723) (`g2`), I created `g3`, this time receiving `sub` instead of `dom`:
```ini
[request_definition]
r = sub, dom, act

[policy_definition]
p = sub, dom, act

[role_definition]
g = _, _, _
g2 = _, _
g3 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && g2(r.dom, p.dom) && g3(r.sub, p.sub) && r.act == p.act
```

_of course, the above does not works_

Over the iterations I removed the `obj` since it didn't make much sense, after all, I am just trying to check whether an action can be performed by someone in a domain. At the end it seems like ACL with domains/tenants + inheritance of domains + inheritance of rules.

Sorry for insisting on this. I don't want to bother. I am just playing with the tool to see the possibilities. I am also checking the [adopters](https://casbin.org/docs/en/adopters) page to see if I can combine with the examples provided on the editor and get what I want. 

____
_Thanks a lot for answering so quickly yesterday_ :heart: :hugs:
