### ISSUE TITLE
Question: Why does the config file contain assignments?

### ISSUE THREAD

**Issue by divoxx** [casbin/casbin#29]
This might no be the appropriate channel for questions but I couldn't find one.

I'm trying to understand the config file in a deeper level but I'm having issues to understand why the config files contain assignments. For example:

```ini
# Request definition
[request_definition]
r = sub, obj, act

# Policy definition
[policy_definition]
p = sub, obj, act

# Policy effect
[policy_effect]
e = some(where (p.eft == allow))

# Matchers
[matchers]
m = r.sub == p.sub && r.obj == p.obj && r.act == p.act
```

Why is `r`, `p`, `e`, `m` necessary? 
Do they have special meaning? 
Is there an example where you could have multiple policy effects or multiple matchers?
Can you have multiple request definitions?
When you have multiple policy definitions, e.g. `p1` and `p2`, does `p` inside the policy effect map to both `p1` and `p2`?

It would be nice to either document those things or simplify the syntax so that it communicates better the usage, flexibility and limits of the system.

**Comment by hsluoyz** [comment]
Hi @divoxx ,

> Why is r, p, e, m necessary? Do they have special meaning?

Just means the header.
r --> request
p --> policy
e --> effect
m --> matcher

> Is there an example where you could have multiple policy effects or multiple matchers?

Yes, multiple r, p, e, m is the goal of design. But for now, it is still not implemented. Because it seems that there's no strong demand for it. So I haven't done it yet. An exception is the RBAC role g. multiple g is supported, like g, g2..

```ini
[role_definition]
g = _, _
g2 = _, _
```

> Can you have multiple request definitions?

Like I said, it is in the design and not implemented yet. Do you have a need for it?

> When you have multiple policy definitions, e.g. p1 and p2, does p inside the policy effect map to both p1 and p2?

You should use p1 and p2 inside policy effect. Because Casbin doesn't do the mapping from p1, p2 to p.

> It would be nice to either document those things or simplify the syntax so that it communicates better the usage, flexibility and limits of the system.

Here's a document: https://github.com/casbin/casbin#syntax-for-models. It may be help you:)

I can't simplify the syntax because it may sacrifice the flexibility. I think documentation is a good way. Can you help me improve the docs?

**Comment by divoxx** [comment]
I guess what's confusing is that the definitions are assigned to a name (r, p, e, m, or anything really) but they are not used anywhere directly.

For example:

* Even if you have multiple `r` defined, you don't do `r1.Enforce(subj, obj, act)` you do `enforcer.Enforce()`; 
* When you're defining `e` you use `some(where(p.eft == allow))` but `p` seems to be mapping to any policy defined, not just the one assigned to `p`
* `m` does not seem to be directly referenced by anything, not in the code, or the configuration file.

The library seems really good and really flexible but I feel like the syntax (or the lack of documentation if those "variables" are relevant) is a big barrier since confusion can very easily lead to vulnerabilities if not defined properly.

I'd be happy to help, but I'm still confused by why and how those "variables" are meant to be used.

**Comment by hsluoyz** [comment]
> Even if you have multiple r defined, you don't do r1.Enforce(subj, obj, act) you do enforcer.Enforce();

My thought is that we differentiate r1, r2, r3 by the number of arguments. For example,

```ini
[request_definition]
r1 = sub, obj, act
r2 = sub, obj, act, xx
r3 = sub, obj, act, xx, yy
```

Then if ``e.Enforce(subj, obj, act)`` is called, we know it's r1. If ``Enforce(subj, obj, act, xx)`` is called, we know it's r2.

> When you're defining e you use some(where(p.eft == allow)) but p seems to be mapping to any policy defined, not just the one assigned to p

I don't quite understand what you mean. ``p.eft`` maps to every matched policy rule's ``eft`` member defined under ``p``. Please see the priority model here: https://github.com/casbin/casbin#examples

> m does not seem to be directly referenced by anything, not in the code, or the configuration file.

m is just the enforcement logic used by ``Enforce()`` function. Please share your way to improve it:)

> The library seems really good and really flexible but I feel like the syntax (or the lack of documentation if those "variables" are relevant) is a big barrier since confusion can very easily lead to vulnerabilities if not defined properly.

Good thing is the test for Casbin is very thorough, so it minimizes the unexpected behaviors. And we can still improve the documentation.

**Comment by divoxx** [comment]
> My thought is that we differentiate r1, r2, r3 by the number of arguments. For example,

Exactly, if it matches based on the number of arguments, why does it need a explicit name `r1`, `r2`?

> I don't quite understand what you mean. p.eft maps to every matched policy rule's eft member defined under p.

Again, if it matches against all policy rules, why does it need a name `p1`, `p2` if those are never referenced directly?

> m is just the enforcement logic used by Enforce() function. Please share your way to improve it

Same here, `m` is never referenced by the name used on the left side of the assignment.

Like I mentioned, it's confusing that the config files allows you to name things if those names are never used. It violates the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) making it harder for a person without any context that those names on the left side of the assignment `=` has no use at all.

It looks like the configuration file could simply be:

```ini
[request_definition]
sub, obj, act
sub, obj, act, xx

[policy_definition]
sub, obj, act

[policy_effect]
some(where (p.eft == allow))

[matchers]
r.sub == p.sub && r.obj == p.obj && r.act == p.act
```

**Comment by divoxx** [comment]
By the way, I don't mean to criticize the project, it's great. Just trying to provide feedback based on my experience trying to understand it.

**Comment by hsluoyz** [comment]
> Exactly, if it matches based on the number of arguments, why does it need a explicit name r1, r2?

There's a chance that r1 and r2 have the same number of args. And Enforce() function can't differentiate them because it uses interface{}.

> Again, if it matches against all policy rules, why does it need a name p1, p2 if those are never referenced directly?

g1 and g2 are used currently. Please see the this example:

RBAC with resource roles | [rbac_model_with_resource_roles.conf](https://github.com/casbin/casbin/blob/master/examples/rbac_model_with_resource_roles.conf)  | [rbac_policy_with_resource_roles.csv](https://github.com/casbin/casbin/blob/master/examples/rbac_policy_with_resource_roles.csv)

> Same here, m is never referenced by the name used on the left side of the assignment.

We can support this:

```ini
[matchers]
m = m1 && m2
m1 = ...
m2 = ...
```

> Like I mentioned, it's confusing that the config files allows you to name things if those names are never used. It violates the principle of least astonishment making it harder for a person without any context that those names on the left side of the assignment = has no use at all.

There're still two reasons.

1. follow the format of .conf/.ini. We know that conf file should have =.
2. Make all definitions in the same format. Maybe e and m don't have the necessity. But I want to keep them in the same format.
3. be consistent with the internal implementation. The implementation is just like this structure: there's one p. And there are p1, p2 and p3 in p. Every px is a definition.

> By the way, I don't mean to criticize the project, it's great. Just trying to provide feedback based on my experience trying to understand it.

Feel free to have a discussion. I always welcome contribution:)

**Comment by hsluoyz** [comment]
Closed as stale.
