### ISSUE TITLE
RoleManager interface to provide custom implementations

### ISSUE THREAD

**Issue by kenjones-cisco** [casbin/casbin#36]
I'm looking to determine if it would be agreeable to switch from RoleManager the struct to RoleManager the interface.

```
type RoleManager interface {
    AddLink(name1 string, name2 string, domain ...string)
    DeleteLink(name1 string, name2 string, domain ...string)
    HasLink(name1 string, name2 string, domain ...string) bool
    GetRoles(name string, domain ...string) []string
    GetUsers(name string) []string
    PrintRoles()
}
```

And the current implementation of RoleManager could become the default implementation.

The only directly impacted part of the code would be
https://github.com/casbin/casbin/blob/master/model/assertion.go

The attribute RM would be interface rbac.RoleManager instead of pointer to an instance of RoleManager. And the implementation of `buildRoleLinks()` https://github.com/casbin/casbin/blob/748b81503e7166d9d43e3d66f3cffae3c8b1ebdd/model/assertion.go#L33 would need a different method for getting a RoleManager to allow a different implementation.

I can start by submitting a PR with the change, and get additional feedback if the above is agreeable.

**Comment by hsluoyz** [comment]
Hi @kenjones-cisco ,

I agree with the idea to make RoleManager an interface. So you can provide a new RoleManager implementation. A question here is whether to make your new implementation inside Casbin code base or provide it as a separate project, like the database adapters now. If your RoleManager needs to be private and out of Casbin, or the implementation is not commonly-used and relies on many 3rd party functionalities (like reading from DB). then we go to the 2nd way. Otherwise, we can go the 1st way. Different ways (1st or 2nd) determine how we design the interface.

**Comment by kenjones-cisco** [comment]
I was assuming taking the approach used for Persistence Adapters.

**Comment by hsluoyz** [comment]
I think you can add an Enforcer API named SetRoleManager. The parameter can be the new RoleManager.

**Comment by kenjones-cisco** [comment]
@hsluoyz I created PR #37 with changes. If you can provide feedback, I can make updates based on the feedback.

**Comment by hsluoyz** [comment]
Merged.
