### ISSUE TITLE
RBAC sessions

### ISSUE THREAD

**Issue by julisch94** [casbin/casbin#43]
Hey there,

I want to realize an **RBAC session concept** that supports the following features:
- (A user can have assigned any number of roles.)
- (A role can have assigned any number of permissions.)
- A user needs to activate one or more of his roles to actually being able to use them.
- This should be done with **sessions**.
- A session consists of _one_ user and _one or more_ roles. It should have a creation date and an expiration date.
- The policy matcher should then only grant access if and only if the requesting user has a running session activating the needed role.
- So: It is *not* sufficient to only have the user-role-assignment. You will always need to activate your needed roles with a session. This supports the principle of [Least Privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege).

This concept is derived from Ravi Sandhu's paper on "role-based access control".

My ideas are the following:
Change the request definition to be

 ```ini
 r = sub, obj, act, time
```

Create a session definition:

 ```ini
s = sub, role, start_time, end_time
```
How am I then able to match an access request. Like this?

 ```ini
m = s(r.sub, p.sub, _, _) && r.obj == p.obj && r.act == p.act && r.time > s.start_time && r.time < s.end_time
```

BTW: All time data will be unix time in nanoseconds, so I hope they'll be comparable.

**Comment by hsluoyz** [comment]
I think you can implement a custom role manager based on [the interface](https://github.com/casbin/casbin/blob/master/rbac/role_manager.go). And you can call ``Enforcer.SetRoleManager()`` to set the role manager to your own. I agree with your session definition. But I think we don't need to use a new name ``s``. We can just use ``g``.

As below, I have allowed to set 4 parameters to role manager's ``AddLink()`` function. So ``Addlink()`` will receive the 4 tuple of ``sub, role, start_time, end_time``.

https://github.com/casbin/casbin/blob/9a33e2dc10f1bcf57f20448254022d91f51cf58c/model/assertion.go#L35-L57

And for role manager's HasLink(), you can still use ``g(r.sub, p.sub, r.time)``. As below, I already allow the 3rd parameter to be passed into ``HasLink(). Although it is the ``domain``, but it can be reused as ``time``. As they are both strings, there's no difference.

https://github.com/casbin/casbin/blob/c1f8fa592a00ea23d117cc88531765fd24f9ca2e/enforcer.go#L246-L272

So now, your role manager will get start_time, end_time from ``AddLink()``, and get ``r.time`` from ``HasLink()``. You can do the time comparison inside the custom role manager now. I think the comparison should not be done directly in the matcher like ``r.time > s.start_time && r.time < s.end_time``, because the session activation should be placed in the role hierarchy. The role hierarchy is checked inside ``g()``. So if you put it in the matcher, it means you can't interact with role hierarchy. For example, Alice inherits Role_A, Role_A inherits Role_B. If the session between Alice and Role_A ends, it means Alice cannot behave as Role_B either. But if the check is done in the matcher, this cannot be done. Because the matcher doesn't know Role_A. It will only check whether Alice and Role_B has an active session.

I will appreciate it if you can provide a session role manager implementation and I will be happy to merge the PR:)

**Comment by hsluoyz** [comment]
Hi. I decide to externalize the session role manager into a separate repo. So only the default role manager will be built-in. All others will be 3rd party and externalized like adapters and watchers. In future, the role manager may retrieve roles from other places like LDAP server, Okta, Auth0 or Azure AD. So such code cannot be placed in Casbin. And I want to make session role manager as a reference example for other people to implement a role manager. Where do you want this separate repo be placed?

**Comment by hsluoyz** [comment]
I have updated the mechanism of role manager. A role manager is a plugin now like the adapter. See here: https://github.com/casbin/casbin#role-manager

This may break your application if it uses the old built-in session role manager. Please update it. Thanks!

**Comment by julisch94** [comment]
Currently I'm not in the office. Gotta talk to my colleagues first. I will tell you on Thursday.
