### ISSUE TITLE
Stack trace in errors

### ISSUE THREAD

**Issue by sagikazarmark** [casbin/casbin#50]
Quoting from the wiki:

> The author believes that Golang error is very unfriendly for developers to debug, because it's only a string and has no faulty call stack information.

This is actually not true. Errors can be anything that implements the error interface.

See https://github.com/pkg/errors for an easy way to include stack trace in errors. Common error handlers can also handle traces like that: https://github.com/airbrake/gobrake/pull/39

**Comment by hsluoyz** [comment]
But this requires to include the library: https://github.com/pkg/errors. Because Casbin is also a library, it means that when someone uses Casbin, he has to import this library too. I feel it's not good to import too many 3rd libraries in a library (like Casbin). So you may notice I even copied some contents like reading cfg to the source instead of importing them. Because I don't want my users to blame that Casbin  is very heavy as it also imports a lot of libs by itself. But maybe I can copy the source of the pkg/errors lib too. Adding some source files are not expensive I think.

**Comment by sagikazarmark** [comment]
You can simply vendor the dependencies, or add Glide or dep. Dep will be the defacto dependency manager for Go instead of go get, so it should not be hard to add.

Also, the library is small, but the provided feature is must have.

**Comment by sagikazarmark** [comment]
Also, this may solve #51 as well

**Comment by hsluoyz** [comment]
It has been 2 years and Casbin v2.x has supported returning errors instead of causing panic. Closed.
