### ISSUE TITLE
[Feature] add the new UpdateGroupingPolicy() API

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin#613]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when when I would like to rename a role and there isn't API for this operation yet.

**Describe the solution you'd like**

1. rename role in policy (can be in the first or the second placeholder)

```
p, admin, data1, read
g, alice, admin
```
becomes:
```
p, administrator, data1, read
g, alice, administrator
```

2. rename role in rbac manager for all domains

```
{ admin: Role { name: "admin", roles: [] }
```
becomes
```
{ administrator: Role { name: "administrator", roles: [] }
```

**Describe alternatives you've considered**

**Additional context**

**Comment by liujiajun** [comment]
Hi all, I would like to work on this issue if no one's taking.

**Comment by liujiajun** [comment]
Since this is my first time contributing to the project, I was wondering anyone could help check the proposal below:

### Proposal 
Add a new RBAC API `EditRoleName(oldName, newName, roleType string) (bool, error)`, where `roleType` can be either `resource` or `subject`.  `rowType` is needed because we need to know which field to update in policy rules. Alternatively, we can use something like `index` instead to achieve greater flexibility.

### Implementation
- Get filtered policies based on `oldName`. Save it to a temporary variable.
- Remove filtered policies based on `oldName`
- Update `oldName` to `newName` in the saved variable.
- Add policies using the saved variable

Admittedly, this is not the most efficient implementation, but it is easy to implement since all the above mentioned operations have APIs.

**Comment by hsluoyz** [comment]
@GopherJ why don't we use `UpdatePolicy()` (https://github.com/casbin/casbin/pull/592) to update the roles in the g policy?

**Comment by nodece** [comment]
It has been implemented by #592.

**Comment by 00LT00** [comment]
@nodece Plz reopen this issues, I just thought of the #592 couldn't resolve this issues. Because it just update `model[p]`.

**Comment by hsluoyz** [comment]
@00LT00 we should have `Enforcer.UpdateGroupingPolicy()` series functions like add and remove.

Can you add this too?

**Comment by 00LT00** [comment]
I am writing, but something has been delayed in the past two weeks

**Comment by hsluoyz** [comment]
Two APIs are added by PR: https://github.com/casbin/casbin/pull/631

- UpdateGroupingPolicy()
- UpdateNamedGroupingPolicy()

But they are not documented. @closetool can you help add these two APIs after here: https://casbin.org/docs/en/management-api#updatepolicies ?
