### ISSUE TITLE
XACML v3.0 Support and Future Adherence to ABAC Standards

### ISSUE THREAD

**Issue by jon-whit** [casbin/casbin#64]
I am seriously considering using casbin as a starting point for a new distributed ABAC authorization system that I want to put into place for enterprise applications.

Casbin stands out to me because of it appears to be relatively well adopted by some big projects leveraging ABAC in the current market, and it appears to be reasonably mature. However, I still have some reservations, and I was hoping that you may be able to answer them for me.

1. Casbin defines its own model and policy syntax and is not developed according to modern OASIS XACML (v3.0) standards. Was there a reason for this decision? Also, are there any plans in the very near future to adopt XACML standards as the means to define the models and policies?

2. I noticed the code frequency metrics have been on a pretty steady decline since May, 2017. Obviously the holiday season has it's impact on developer productivity in the November and December months, but a steady decline over that period of time suggests that project support is dying or discontinuing slowly. Is there a reason for this? Where do you see this project in a year or two?

**Comment by hsluoyz** [comment]
Thanks for considering it!

1. It is intended not to adopt the XACML standard. Because of several reasons: 1) XACML is hard to learn and write, to achieve the same authorization effect. 2) I doubt XACML cannot be the same expressive as Casbin. 3) At present, although XACML is a well-known language, only a few Java projects actually use it. There's even no mature XACML implementation in Golang. And I believe the complicated design of XACML and the XML grammar are not consistent with the design philosophy of Golang. 4) Do you have any particular reason that drives you to use XACML? or it's just a tendency to use a standard? Maybe we can discuss about it a little.

2. The recent commits become less because it turns to a relatively mature project. I'm always open-minded for reasonable improvements. Because Casbin uses a plugin based design. A lot of functionalities can be enhanced by developing a new plugin, like the storage plugin, the role manager plugin, etc. People can always contribute to it to make it a community. I personally want to extend Casbin to Java, because Java is another large market for server-side applications. You may already see the [jCasbin](https://github.com/casbin/jcasbin) project. But it is slowly developed because there's no strong need for it. However, Casbin has become the largest (most starred) project for Golang's authorization and is adopted by vendors like Intel, Cisco, IBM (someone from there sent issues). I want to make it at least the authorization standard for Golang.

**Comment by jon-whit** [comment]
Hi @hsluoyz, thanks for getting back with me so promptly. I appreciate your response. Let's continue the discussion!

XACML's primary use  and my understanding of it's primary role, is to create a standardized policy language that is used between Policy Enforcement Points (PEPs) and Policy Decision Points (PDPs). It allows PEPs to be decoupled from the PDPs that it calls upon. Maybe you could give an example where XACML isn't as expressive as the Casbin syntax. Better yet, maybe you could show me an example of a slightly more complex RBAC and ABAC (hybrid) model where actors seek to take an action on a resource and the actors can be users, groups of users or perhaps APIs or other systems. More generally, it would be nice to see more ABAC examples or documentation for this project. You have labeled it as a supported model, but you have not yet quite developed more examples around it.

Certainly, my tendency to use XACML is due to the fact that is the most widely adopted standard when it comes to ABAC. XACML has even been pushed down by NIST and OASIS, which are widely accepted standards organizations.

My immediate need is to serve authorization needs for Go apps that define microservices in the Google Cloud Platform. However, I have an existing monolithic Java app that defines it's own user and group permissions. There may be a future need to use the same authorization service for that monolith. How would this best be achieved with Casbin? Do you recommend exposing a RESTful API that calls into Casbin?

**Comment by hsluoyz** [comment]
> Maybe you could give an example where XACML isn't as expressive as the Casbin syntax.

For example, XACML does not support RBAC hierarchical roles, like A inherits role B, B inherits role C.

> Better yet, maybe you could show me an example of a slightly more complex RBAC and ABAC (hybrid) model where actors seek to take an action on a resource and the actors can be users, groups of users or perhaps APIs or other systems.

You can add a ``type`` field to the policy and request. For users it will be ``user``, for API or systems it will be ``API`` or ``service``. Casbin can handle this well.

> More generally, it would be nice to see more ABAC examples or documentation for this project. You have labeled it as a supported model, but you have not yet quite developed more examples around it.

Besides the official examples, you can also see how our adopters are using it. 

> Certainly, my tendency to use XACML is due to the fact that is the most widely adopted standard when it comes to ABAC. XACML has even been pushed down by NIST and OASIS, which are widely accepted standards organizations.

What I worried is that XACML lacks support for big vendors, like in large cloud providers like AWS, Microsoft, and open source leaders like Google. Famous Java security project Shiro even doesn't support XACML standard. XACML is not friendly even for me (I'm a researcher that studied authorization). In my humble opionion, It's nearly half-dead. I think Casbin should make authorization as easy as possible, not complicate things.

> My immediate need is to serve authorization needs for Go apps that define microservices in the Google Cloud Platform. However, I have an existing monolithic Java app that defines it's own user and group permissions. There may be a future need to use the same authorization service for that monolith. How would this best be achieved with Casbin? Do you recommend exposing a RESTful API that calls into Casbin?

As I said, jCasbin is an option. But it needs some man power to finish its port from Golang to Java. Another option is using Casbin as a service. The candidates are listed here: https://github.com/casbin/casbin#how-to-use-casbin-as-a-service

**Comment by hsluoyz** [comment]
Closed as stale.

**Comment by hsluoyz** [comment]
@jon-whit  FYI, jCasbin is completed and usable now, please see: https://github.com/casbin/jcasbin

**Comment by josefsabl** [comment]
I just wanted to say that I am just researching the authorization topic at the moment and had EXACTLY the same questions that got asked. I am totally satisfied with answers and decided to use casbin instead of XACML.
