### ISSUE TITLE
[Question] Is it possible to not use memory + watchers for distributed updates (IE disable caching?)

### ISSUE THREAD

**Issue by trevoro** [casbin/casbin#679]
Hi Team,

First of all great library; it's obviously popular and well suited to the task.
I was surprised after spending some time implementing this library in a project that the policies are stored in memory. If I was running this in production on a single server that wouldn't be so much of an issue. But it's 2020 and nobody actually does that. I realize that there's a distributed update watching mechanism available for hooks to just reload everything, but I'm sort of confused about why the option does not exist which **disables** the cache locally instead?

Should we not be able to optionally choose to have a local cache or not?
I don't have a latency problem with my policy storage engine and I'm OK with the "performance hit" of a round trip to a central service with the policies. But I cannot seem to opt out of the cache and feel forced to adopt a distributed gossip protocol or one based on Redis or Pubsub to just synchronize state.

Is it possible to disable the local cache with some unknown setting?
Is it possible for us to provide the cache as another interface rather than a deep seeded structure?

**Comment by hsluoyz** [comment]
@trevoro you can explicitly call `LoadPolicy()` (load all rules) or `LoadFilteredPolicy()` (load a part of all rules with a filter) before the `Enforce()` call.

See:

- https://casbin.org/docs/en/adapters#loadsave-at-run-time
- https://casbin.org/docs/en/policy-subset-loading

**Comment by nodece** [comment]
This is one of the ways.
> @trevoro you can explicitly call LoadPolicy() (load all rules) or LoadFilteredPolicy() (load a part of all rules with a filter) before the Enforce() call.

During this time, I'm still exploring how to solve the distributed updates, so we propose [dispatcher](https://casbin.org/docs/en/dispatchers) concept. 

I implemented a [casbin-hraft-dispatcher](https://github.com/nodece/casbin-hraft-dispatcher) base on Hashicorp's Raft, but it's still under development.

I welcome any developer to contribute. for me, I'm still inexperienced in distributed system.

### How it works

In a distributed system, we have many casbin nodes running, and many casbin nodes using the a shared adapter to store data. When policy changes, it will be persisted into the database through `Adapter`, then `Watcher` will be called to notify other nodes to reload the policy data. There may be IO problem hidden here.

In dispatcher, I rely on the raft protocol to implement that each node maintains its own policy instead of using the shared adapter. When the policy needs to be updating, casbin will forward the request to the dispatcher. The dispatcher synchronizing the changed policy to each node by raft, when each node receives the data, they will synchronize these policies to casbin memory.

**Comment by trevoro** [comment]
Hey thanks for the explanation; that lines up with how I had modelled the behaviour in my head. 
I think having an option or structure that has different behaviour out-of-the-box makes sense for lots of folks that don't have high volume, but still have distributed environments. For example, the _second_ you run an app using Casbin in a kubernetes environment you run into this distributed state problem. Raft is definitely the best gossip protocol for ensuring that systems in the cluster have up to date state, but being forced to setup another service to use Casbin is overkill.

What if Casbin could do synchronous reads and writes to the Adapter? This would work without any async update mechanisms like watchers, or dispatchers. It comes at the cost of some latency, but if it's an explicit option then it should be fairly easy for folks to understand the trade-offs. It doesn't have to be the default behaviour at all; just an option for setting up casbin quickly & easily without writing before / after methods for *I think* most people.

**Comment by hsluoyz** [comment]
@trevoro what do you mean by `do synchronous reads and writes to the Adapter`?

**Comment by hsluoyz** [comment]
Closed as stale.
