### ISSUE TITLE
Policies and Model per resource

### ISSUE THREAD

**Issue by faxal** [casbin/casbin#72]
I have a use case where policies and model defer per resource. Model and policies depend on the type of resource, hence I want to attach policies to resource.

For example when I fetch resource A from database, it will contain all the policies attached to it and application will load the model based on resource type and check if certain action is allowed for a subject.

Is this currently possible? I ask because all examples point to single policy storage location and enforcer is 
loaded at the initialization phase of an application. This gives me the impression that `casbin` is optimized for initialize ones and check many and *not* initialize many check few.

With the above use case enforcers need to be initialized based on the resource type as model might change depending on resource type during application run-time.

I hope that was clear.

**Comment by hsluoyz** [comment]
It's a good scenario. But the design for multiple enforcer usage largely depends on how to store the model and policies. The policies are attached to a resource. Where do you want to store the policies and model?

**Comment by faxal** [comment]
What I imagined is it will be stored along with the resource. For example if the resource is a file, policies would be an attribute of the file and in case of a resource that is stored in a database I imagine policies would be stored as text blob or maybe even JSON in a column.

I would guess that `casbin` shouldn't worry about how it gets stored and be optimized for a way dynamically change enforcer based on model and policies at runtime. 

Or maybe initialize a new enforcer for each request? Is that expensive?

**Comment by hsluoyz** [comment]
> What I imagined is it will be stored along with the resource. For example if the resource is a file, policies would be an attribute of the file and in case of a resource that is stored in a database I imagine policies would be stored as text blob or maybe as JSON in a column.

It seems that you wants to use both model and policy as strings. Model is just a string. With JSON adapter described [here](https://github.com/casbin/casbin#policy-persistence) you can also make policy a JSON string. 

> Or maybe initialize a new enforcer for each request? Is that expensive?

Enforcer is just a wrapper for model and policy rules. It is not expensive. But you also don't need to initialize a new enforcer for each request. For your case, since model is bound to resource type. You can initialize an enforcer for each model (each type of resource). For example, build a map from resource type to enforcer. Then dynamically change the policy for each enforcer. You can directly set an adapter which represents a new policy, or modify the policy rules with Casbin Management API.

**Comment by faxal** [comment]
> Enforcer is just a wrapper for model and policy rules. It is not expensive. 
If that is the case what you suggested could be a good solution. 

Thanks
