### ISSUE TITLE
[Bug] It is impossible to define my own group name

### ISSUE THREAD

**Issue by SgtDaJim** [casbin/casbin#841]
In my code, I new a model as below:
![image](https://user-images.githubusercontent.com/10288044/125790729-90037915-c3db-4845-9afd-08bdeb97413e.png)
and the Enforcer is normally initialized.
But when i call the function AddRoleForUserInDomain of Enforcer, it panic:
![image](https://user-images.githubusercontent.com/10288044/125791127-907538d0-ddc2-42d1-bf44-c41eae36d9a6.png)
After I check the code, I found that in the calling stack, the function AddGroupingPolicy of Enforcer will use "g" as variable "ptype" to pass into the function AddNamedGroupingPolicy mandatory:
![image](https://user-images.githubusercontent.com/10288044/125791801-dbdd66a1-080f-4d6d-ba35-9aa49638ad19.png)
So the process panicked becase the AssertionMap has no key "g".
It is nonsense.
If I have to use the group name "g",  it should return an error at the beginning of initializing the enforcer.

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@SgtDaJim Thanks for your suggests. Your are right, casbin supports custom group name in core codes. But in some edge codes, they cann't support this feature. Because method signature does not satisfy its requirement.
So I suggest you using the core methods, such as AddNamedGroupingPolicy, or change group name to 'g'.

**Comment by SgtDaJim** [comment]
> @SgtDaJim Thanks for your suggests. Your are right, casbin supports custom group name in core codes. But in some edge codes, they cann't support this feature. Because method signature does not satisfy its requirement.
> So I suggest you using the core methods, such as AddNamedGroupingPolicy, or changing group name to 'g'.

So how can i distinguish the core methods and the edge methods? I don't think i read about it on docs

**Comment by closetool** [comment]
@SgtDaJim Methods in file management_api and rbac_api are most likely to be the edge.

**Comment by hsluoyz** [comment]
@SgtDaJim AddDef()'s first arg is "sec", it can be "p" or "g". The second arg is "ptype" (or "key").

For sec "g", its ptype is usually "g" or "g2" or "g3", etc. Most RBAC APIs will use "g" ptype by default. But you changed the ptype to "sub_group". This is why your code doesn't work. To resolve it, either:

1. Use "g" instead of "sub_group" as ptype.
2. Use the "xxxNamedxxx" APIs in Management APIs like: https://casbin.org/docs/en/management-api#addnamedgroupingpolicy , which allows you to specify a custom ptype.
