### ISSUE TITLE
Changes suggestion on LoadFilteredPolicy

### ISSUE THREAD

**Issue by mariohov** [casbin/casbin#93]
I would like to load a subject and object Policy from MongoDB when I need to check permission with Enforce function.
First I use ``HasPermissionForUser`` function. When it returns false, I call ``LoadFilteredPolicy`` to load user/object Policies to the model.
I saw that all the time I call ``LoadFilteredPolicy``, Enforcer clears the model.
My suggestion is to add a bool argument on ``LoadFilteredPolicy`` to check when we want a cleared Model or just append more Policy to existing model.

Example:
```go
func (a *aclMongoRepository) Enforce(acl Acl) (bool, error) {
	if !a.enforcer.HasPermissionForUser(acl.subject, acl.permission.object, acl.permission.action) {
		filter := &bson.M{"v0": acl.subject, "v1": acl.permission.object}
		a.enforcer.LoadFilteredPolicy(filter)
	}
	return a.enforcer.EnforceSafe(acl.subject, acl.permission.object, acl.permission.action)
}
```

**Comment by hsluoyz** [comment]
Sounds good to me. You can make a PR about it. Make the bool parameter optional.

**Comment by hsluoyz** [comment]
``LoadPolicy()`` or ``LoadFilteredPolicy()`` always clears the current policy rules (in Casbin enforcer's cache) and loads a new bunch of policy rules from the adapter. And it's difficult to support it because it needs to handle the duplicates. So I suggest you can implement this function on your own. If you want and it's appropriate, you can also contribute it back to Casbin via PR.
