### ISSUE TITLE
[Question] Store resource/object attributes and evaluating condition inside the policies

### ISSUE THREAD

**Issue by taosx** [casbin/casbin#952]
**What's your scenario? What do you want to achieve?**
Currently I'm using a combination of RBAC and ABAC but I want to be able to enforce abac without reaching for the resource database, to that end I'm thinking of storing the resource/object attributes directly in the policy file but I don't know how to use that combined with resource groups.

**Your model:**

```ini
[request_definition]
r = sub, act, res

[policy_definition]
p = sub, act, res, cond
p2 = res, attr

[role_definition]
# user roles
g = _, _
# resource groups
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) \
    && g2(r.res, p.res) \
    && r.act == p.act \
    && eval(p.cond)
```

**Your policy:**

```
p, role:customer, write, resource_group:customer_data, attr.assigned_to == r.sub

# attribute storage (not working, example of what i want to do)
p2, resource:profile:7421, { assigned_to:  'user:0174' }

# roles
g, user:0174, role:customer

# resource group
g2, resource:profile:7421, resource_group:customer_data
```

**The problem is that I don't know how to make the condition `attr.assigned_to == r.sub` to retrieve the attr from another policy line.** 

**Your request(s):**

```
user:0174,  resource:profile:7421, write ---> false/error (expected: true)
```

I've also thought of just having a single policy model (p) and remove resource groups but then i'm afraid the number of policies would explode, not all resources have a condition attached.

**Comment by hsluoyz** [comment]
@abichinger @Abingcbc @sagilio @nodece

**Comment by Abingcbc** [comment]
It seams that Casbin currently only supports map one request type to one policy type. https://casbin.org/docs/en/syntax-for-models#multiple-sections-type

> By default these four sections should correspond one to one. Such as your r2 will only use matcher m2 to match policies p2.

So, `r` will not match any policy in `p2`.

**Comment by Abingcbc** [comment]
Maybe this is a new feature for Casbin? @hsluoyz

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by taosx** [comment]
> Maybe this is a new feature for Casbin? @hsluoyz

Maybe, I see the following ways around it:
1. Have the data in the request (I don't really want to go this way as it forces me to read from another place)
2. Have a custom function (I'm still working on this)
3. Extend casbin (as you said)

Currently I'm exploring the custom function route and defining custom functions (wasm) that are triggered by policies in the following way:
model: `m = g(r.sub, p.sub) && g2(r.res, p.res)  && r.act == p.act && runWasmByID(p.custom_fn_id, r.sub, r.res)`
policy: `p, role:agent, write, resource:customer_data, wasm_id`

**Comment by shayura** [comment]
I'm in a similar predicament. None of my attempts to extend an existing RBAC model[^1] to include ABAC rules, with a different number of arguments, using separate `p2`, `r2` and `m2` elements seem to work.

This is my RBAC model:

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _
g3 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g2(r.sub, p.sub) || g(r.sub, p.sub, r.dom)) \
  && keyMatch(r.dom, p.dom) \
  && keyMatch(r.obj, p.obj) \
  && r.act == p.act || g3(r.sub, "root")
```

Whereas the example policy is:

```
; Role privileges
p, author, *, book/*, edit
p, publisher, *, book/*, publish

; Martin and Alice are two authors in different organisations
g, martin, author, tusks_publishing_co
g, alice, author, acme_publishing

; Bob is a publisher
g2, bob, publisher

; Super is a root account
g3, super, root
```

The above model worked fine. However, things started falling apart when I extended the model with ABAC rules. Similarly to @taosx, I've tried to merging the ABAC expressions over `r2` and `p2` inside the original `m` matcher using logical operators but couldn't get it to work. 

Then I went with a separate matcher `m2` to accompany `r2` and `p2`:

```ini
[request_definition]
r = sub, dom, obj, act
r2 = sub, obj, act

[policy_definition]
p = sub, dom, obj, act
p2 = sub_rule, obj, act

[role_definition]
g = _, _, _
g2 = _, _
g3 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g2(r.sub, p.sub) || g(r.sub, p.sub, r.dom)) \
  && keyMatch(r.dom, p.dom) \
  && keyMatch(r.obj, p.obj) \
  && r.act == p.act || g3(r.sub, "root")
m2 = eval(p2.sub_rule) && r2.obj == p2.obj && r2.act == p.act
```

When using this model in Casbin.NET, existing RBAC tests were still succeeding, but the call to `Enforce` would always fail for one of two reasons:
- The number of `requestValues` didn't match the tokens in the request `r`, even though `r2` should have been used.
- (By artificially making the token counts match) the parser failed with an exception `Argument list incompatible with delegate expression (at index 1)`, because it bound the `requestValues` against `r` instead of `r2`.

As far as I understand, I could work around this issue by splitting the RBAC and ABAC model into separate `.conf` files and making consecutive `Enforce` calls. Am I wrong to think this? I would expect Casbin to be able to switch from `p` or `p2` based on the number of arguments and/or keep trying until all options are exhausted.

Should Casbin support `Enforce` calls against models that define multiple requests with different number of arguments? E.g.

```cs
// e is a single instance of the Enforcer loaded with the "unified" RBAC + ABAC model.
e.Enforce("martin", "tusks_publishing_co", "book/1", "publish")
e.Enforce(new {Id = 1}, new {Publisher = 1}, "publish")
```

[^1]: RBAC with tenants and super user.

**Comment by taosx** [comment]
I realized that I was adding abstractions and relationship modeling on top of casbin to the point where I had trouble reasoning about it, it was not a fit for my use-case. I migrated to another solution.
